package:
  name: 'lightcurve'
  version: '0.6.2'

source:
  git_url: https://github.com/justincely/lightcurve.git
  git_rev: v0.6.2

requirements:
  build:
    - astropy
    - cython
    - scipy
    - matplotlib
    - setuptools
    - numpy >=1.9
    - numba >=0.24.0
    - llvmlite >=0.9.0
    - nose
    - six
    - python

  run:
    - astropy
    - cython
    - scipy
    - matplotlib
    - setuptools
    - numpy >=1.9
    - numba >=0.24.0
    - llvmlite >=0.9.0
    - nose
    - six
    - python

test:
  requires:
    - astropy
  imports:
    - lightcurve

about:
  home: https://github.com/justincely/lightcurve
  license: BSD
